#helm:generate helmc tpl -d tpl/values.toml -o manifests/jenkins-data-pvc.yaml $HELM_GENERATE_FILE
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: jenkins
  labels:
    app: jenkins
    provider: jenkins-server
    heritage: bitnami
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .jenkinsDataClaimSize }}
