apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildkite-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: buildkite-agent
        heritage: helm
    spec:
      containers:
        - name: buildkite-agent
          image: buildkite/agent
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            # BUILDKITE AGENT ENV VARS
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent-token
                  key: token
            - name: BUILDKITE_AGENT_META_DATA
              value: "role=deploy"
          volumeMounts:
            - name: var-run-docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: var-run-docker-sock
          hostPath:
            path: /var/run/docker.sock
