apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildkite-agent-builder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: buildkite-agent-builder
        heritage: helm
    spec:
      containers:
        - name: buildkite-agent
          image: buildkite/agent:ubuntu-docker
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 400m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
            # BUILDKITE AGENT ENV VARS
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent-builder-token
                  key: token
            - name: BUILDKITE_AGENT_META_DATA
              value: "role=builder"
            - name: DIND
              value: "true"
          volumeMounts:
            - name: var-lib-docker
              mountPath: /var/lib/docker
      volumes:
        - name: var-lib-docker
          emptyDir: {}
