apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis-master
    provider: redis
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        provider: redis
        heritage: helm
    spec:
      containers:
      - name: master
        image: gcr.io/google_containers/redis:e2e
        ports:
        - containerPort: 6379
