#helm:generate helmc template -o $HELM_GENERATE_DIR/manifests/buildkite-agent-token-secret.yaml -d $HELM_GENERATE_DIR/tpl/settings.toml $HELM_GENERATE_DIR/tpl/buildkite-agent-token-secret.yaml
kind: "Secret"
apiVersion: "v1"
metadata:
  name: "buildkite-agent-token"
  labels:
    heritage: helm
type: Opaque
data:
  token: "{{ b64enc .agent_token.token }}"
